version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          registry: $DOCKER_REGISTRY
      - docker/build:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_TAG
          registry: $DOCKER_REGISTRY
  push-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - docker/push:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_TAG
          registry: $DOCKER_REGISTRY

workflows:
  build-deploy:
    jobs:
      - build-docker-image
      - push-docker-image:
        # only pushes on tags
        filters:
          tags:
            only: /.*/
