[build]

# Target musl-libc by default when running Cargo
target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin22.4-clang"
ar = "x86_64-apple-darwin22.4-ar"

[target.aarch64-apple-darwin]
linker = "arm64e-apple-darwin22.4-clang"
ar = "arm64e-apple-darwin22.4-ar"
